import { Product, DigitalProduct, Banner, Seller } from "../types";

export const mockSeller: Seller = {
  id: "1",
  name: "PrintMaster3D",
  rating: 4.8,
  totalSales: 1240,
  verified: true,
  postalCode: "01310100", // CEP fictício — será preenchido pelo perfil real do vendedor
};

export const mockBanners: Banner[] = [
  {
    id: "1",
    imageUrl: "https://placehold.co/800x300/f97316/ffffff?text=Impressoras+3D",
    title: "Impressoras com até 40% OFF",
    subtitle: "Aproveite as melhores ofertas em impressoras 3D",
    actionLabel: "Ver ofertas",
    targetScreen: "Products",
  },
  {
    id: "2",
    imageUrl: "https://placehold.co/800x300/0f172a/f97316?text=Filamentos+Premium",
    title: "Filamentos Premium",
    subtitle: "PLA, PETG, ABS e muito mais",
    actionLabel: "Comprar agora",
    targetScreen: "Products",
  },
  {
    id: "3",
    imageUrl: "https://placehold.co/800x300/1e293b/ffffff?text=Arquivos+STL",
    title: "Arquivos STL Exclusivos",
    subtitle: "Modelos prontos para imprimir",
    actionLabel: "Ver modelos",
    targetScreen: "Digital",
  },
];

export const mockProducts: Product[] = [
  {
    id: "1",
    title: "Bambu Lab A1 Mini Impressora 3D",
    description: "Impressora 3D de alta velocidade com calibração automática",
    price: 2199.9,
    originalPrice: 2799.9,
    images: ["https://placehold.co/400x400/1e293b/f97316?text=Bambu+A1+Mini"],
    category: "impressoras",
    seller: mockSeller,
    rating: 4.9,
    reviewCount: 328,
    inStock: true,
    freeShipping: true,
    condition: "new",
    createdAt: "2024-01-10",
  },
  {
    id: "2",
    title: "Filamento PLA+ 1kg Preto - eSUN",
    description: "Filamento PLA+ de alta qualidade, 1.75mm",
    price: 89.9,
    originalPrice: 109.9,
    images: ["https://placehold.co/400x400/1e293b/f97316?text=PLA%2B+Preto"],
    category: "filamentos",
    seller: mockSeller,
    rating: 4.7,
    reviewCount: 512,
    inStock: true,
    freeShipping: false,
    condition: "new",
    createdAt: "2024-01-15",
  },
  {
    id: "3",
    title: "Creality Ender 3 V3 SE",
    description: "Impressora 3D FDM ideal para iniciantes, auto-nivelamento",
    price: 899.9,
    originalPrice: 1199.9,
    images: ["https://placehold.co/400x400/1e293b/f97316?text=Ender+3+V3"],
    category: "impressoras",
    seller: mockSeller,
    rating: 4.6,
    reviewCount: 891,
    inStock: true,
    freeShipping: true,
    condition: "new",
    createdAt: "2024-01-20",
  },
  {
    id: "4",
    title: "Kit Bicos Nozzle MK8 0.4mm (10 unidades)",
    description: "Bicos de latão compatíveis com Ender e outros modelos",
    price: 34.9,
    images: ["https://placehold.co/400x400/1e293b/f97316?text=Nozzle+Kit"],
    category: "pecas",
    seller: mockSeller,
    rating: 4.5,
    reviewCount: 203,
    inStock: true,
    freeShipping: false,
    condition: "new",
    createdAt: "2024-02-01",
  },
  {
    id: "5",
    title: "Filamento PETG Transparente 1kg",
    description: "PETG cristal para peças técnicas e decorativas",
    price: 119.9,
    originalPrice: 149.9,
    images: ["https://placehold.co/400x400/1e293b/f97316?text=PETG+Transparente"],
    category: "filamentos",
    seller: mockSeller,
    rating: 4.8,
    reviewCount: 176,
    inStock: true,
    freeShipping: false,
    condition: "new",
    createdAt: "2024-02-05",
  },
  {
    id: "6",
    title: "Raspberry Pi 4 4GB - Octoprint Ready",
    description: "Controle remoto para impressoras 3D via Octoprint",
    price: 349.9,
    images: ["https://placehold.co/400x400/1e293b/f97316?text=Raspberry+Pi+4"],
    category: "hardware",
    seller: mockSeller,
    rating: 4.9,
    reviewCount: 97,
    inStock: false,
    freeShipping: true,
    condition: "new",
    createdAt: "2024-02-10",
  },
];

export const mockDigitalProducts: DigitalProduct[] = [
  {
    id: "d1",
    title: "Suporte Articulado para Smartphone",
    description: "Suporte impresso em 3D, totalmente articulável",
    price: 9.9,
    thumbnail: "https://placehold.co/400x400/0f172a/f97316?text=STL+Suporte",
    previewImages: [],
    category: "stl",
    formats: ["STL", "3MF"],
    formatFiles: {},
    seller: mockSeller,
    rating: 4.9,
    reviewCount: 642,
    downloadCount: 1820,
    printDifficulty: "easy",
    supportRequired: false,
    createdAt: "2024-01-05",
  },
  {
    id: "d2",
    title: "Caixa Organizadora Modular — Pack 5 peças",
    description: "Sistema modular encaixável para organização de mesa",
    price: 19.9,
    originalPrice: 29.9,
    thumbnail: "https://placehold.co/400x400/0f172a/f97316?text=STL+Organizer",
    previewImages: [],
    category: "bundle",
    formats: ["STL", "STEP", "3MF"],
    formatFiles: {},
    seller: mockSeller,
    rating: 4.7,
    reviewCount: 318,
    downloadCount: 940,
    printDifficulty: "easy",
    supportRequired: false,
    createdAt: "2024-01-18",
  },
];
